name: Build Qt Project (Windows MinGW)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.19'
        arch: 'win64_mingw81' # MinGW 8.1 64位
        host: 'windows'

    - name: 设置 CMake
      uses: lukka/get-cmake@latest

    - name: 配置 CMake
      run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.Qt6_Dir }}"

    - name: 构建
      run: cmake --build build --config Release
