name: Build Qt Project (Windows MinGW)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Qt
      uses: jurplel/install-qt-action@v4
      with:
        target: 'desktop'
        arch: 'win64_llvm_mingw'
        use-official: true
        host: 'windows'

    - name: 安装 MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gettext
          sed
    
    - name: 设置 PATH 以包含 MSYS2 工具
      run: echo "C:\msys64\usr\bin;C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: powershell
          
    - name: 设置 CMake
      uses: lukka/get-cmake@latest

    - name: 配置 CMake
      run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.Qt6_Dir }}"

    - name: 构建
      run: cmake --build build --config Release
      
    - name: WinQTDeploy
      run: |
        "D:\a\qc-devcfg-parser\Qt\6.8.3\llvm-mingw_64\bin\windeployqt.exe" build\src\qt\qc_devcfg_parser_qt.exe

    - name: 创建Tag
      id: set_tag_name
      shell: pwsh
      run: |
        $current_time = Get-Date -Format "yy.MM.HH.mm"
        "TAG_NAME=release-$current_time" | Out-File -FilePath $env:GITHUB_ENV -Append
        "RELEASE_NAME=Release $current_time" | Out-File -FilePath $env:GITHUB_ENV -Append
        Compress-Archive -Path build\* -DestinationPath build.zip

    - name: 创建发布
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: true

    - name: 发布
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build.zip
        asset_name: qc-devcfg-parser
        asset_content_type: application/x-7z-compressed
