name: Build Qt Project (Windows MinGW)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.19'
        arch: 'win64_mingw' # MinGW 8.1 64位
        host: 'windows'

    - name: 安装 MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gettext
          sed
    
    - name: 设置 PATH 以包含 MSYS2 工具
      run: echo "C:\msys64\usr\bin;C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: powershell
          
    - name: 设置 CMake
      uses: lukka/get-cmake@latest

    - name: 配置 CMake
      run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.Qt6_Dir }}"

    - name: 构建
      run: cmake --build build --config Release
